#!/usr/bin/env bash
# Start the Hermes execution harness (gateway mode) against local Bonsai.
# Generates the Hermes env file on first run; all values overridable via .env.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
[[ -f "$ROOT/.env" ]] && { set -a; # shellcheck disable=SC1091
  source "$ROOT/.env"; set +a; }

BONSAI_URL="${BONSAI_URL:-${BONSAI_BASE_URL:-http://127.0.0.1:8091}/v1}"
HERMES_PORT="${HERMES_PORT:-8642}"
HERMES_KEY="${HERMES_KEY:-bonsai-local}"
ENVFILE="${HERMES_ENV:-${HERMES_ENV_FILE:-$HOME/.hermes/.env.bonsai-local}}"
MODEL_ID="${BONSAI_MODEL_ID:-Ternary-Bonsai-2-27B-PQ2_0}"

if ! command -v hermes >/dev/null 2>&1; then
  echo "hermes CLI not found." >&2
  echo "Install with: INSTALL_HERMES=1 ./scripts/bootstrap.sh" >&2
  echo "  (or: python -m pip install --user -U hermes-agent)" >&2
  exit 1
fi

# Discover the model from the running server when possible (spec: /v1/models).
DISCOVERED="$(curl -fsS -m 3 "$BONSAI_URL/models" 2>/dev/null \
  | python3 -c "import json,sys;print((json.load(sys.stdin).get('data') or [{}])[0].get('id',''))" 2>/dev/null || true)"
[[ -n "$DISCOVERED" ]] && MODEL_ID="$DISCOVERED"
echo "Bonsai model via /v1/models: $MODEL_ID"

# Detect installed Hermes config syntax instead of assuming stale keys.
HERMES_HELP="$(hermes --help 2>&1 || true)"
if grep -qi 'gateway' <<<"$HERMES_HELP"; then
  START_CMD=(hermes gateway)
else
  echo "WARN: installed hermes has no 'gateway' subcommand; trying 'hermes serve'" >&2
  START_CMD=(hermes serve)
fi

mkdir -p "$(dirname "$ENVFILE")"
cat > "$ENVFILE" <<EOF
# Generated by scripts/start-hermes.sh — local Bonsai endpoint. No real secrets.
OPENAI_API_KEY=${OPENAI_API_KEY:-local}
OPENAI_BASE_URL=$BONSAI_URL
BONSAI_MODEL=$MODEL_ID
API_SERVER_ENABLED=true
API_SERVER_KEY=$HERMES_KEY
API_SERVER_PORT=$HERMES_PORT
TERMINAL_LOCAL_PERSISTENT=true
EOF
echo "wrote $ENVFILE"

# Export for the gateway process (merge into current env).
set -a
# shellcheck disable=SC1090
source "$ENVFILE"
set +a

echo "starting: ${START_CMD[*]} (port $HERMES_PORT)"
exec "${START_CMD[@]}"
